#
#spring:
#  datasource:
#    url: jdbc:postgresql://lala:5432/lab1
#    username: eoeqs
#    password: eoeqs
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          client-id: 22ab263505f3407382296692d3f31087
#          client-secret: 7e05ff83dbd449f09cac6d8217b42012
#          introspection-uri: 'https://login.yandex.ru/info?format=jwt'
#
#
#logging:
#  level:
#    org:
#      springframework: trace
#
